import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles(theme => ({
  st0: { fill: 'url(#SVGID_1_)' },
  st1: { fill: 'url(#SVGID_2_)' },
  st2: { fill: 'url(#SVGID_3_)' },
  st3: { fill: 'url(#SVGID_4_)' },
  st4: { fill: 'url(#SVGID_5_)' },
  st5: {
    fill: 'none',
    stroke: 'url(#SVGID_6_)',
    strokeWidth: 0.5,
    strokeMiterlimit: 10,
  },
  st6: { fill: 'url(#SVGID_7_)' },
  st7: { fill: 'url(#SVGID_8_)' },
  st8: { fill: 'url(#SVGID_9_)' },
  st9: { fill: 'url(#SVGID_10_)' },
  st10: { fill: 'url(#SVGID_11_)' },
  st11: { fill: 'url(#SVGID_12_)' },
  st12: {
    fill: 'none',
    stroke: 'url(#SVGID_13_)',
    strokeWidth: 0.5,
    strokeMiterlimit: 10,
    strokeDasharray: 5.49,
  },
  st13: { fill: 'url(#SVGID_14_)' },
  st14: { fill: 'url(#SVGID_15_)' },
  st15: { fill: 'url(#SVGID_16_)' },
  st16: { fill: 'none', stroke: 'url(#SVGID_17_)', strokeWidth: 0.5, strokeMiterlimit: 10 },
  st17: { fill: 'none', stroke: 'url(#SVGID_18_)', strokeWidth: 0.5, strokeMiterlimit: 10 },
  st18: { fill: 'none', stroke: 'url(#SVGID_19_)', strokeWidth: 0.5, strokeMiterlimit: 10 },
  st19: { fill: 'url(#SVGID_20_)' },
  st20: { fill: 'url(#SVGID_21_)' },
  st21: { fill: 'url(#SVGID_22_)' },
  st22: { fill: 'url(#SVGID_23_)' },
  st23: { fill: 'url(#SVGID_24_)' },
  st24: { fill: 'url(#SVGID_25_)' },
  st25: { fill: 'url(#SVGID_26_)' },
  st26: { fill: 'url(#SVGID_27_)' },
  st27: { fill: 'url(#SVGID_28_)' },
  st28: { fill: 'url(#SVGID_29_)' },
  st29: { fill: 'url(#SVGID_30_)' },
  st30: { fill: 'url(#SVGID_31_)' },
  st31: { fill: 'url(#SVGID_32_)' },
  st32: { fill: 'url(#SVGID_33_)' },
  st33: { fill: 'url(#SVGID_34_)' },
  st34: { fill: 'url(#SVGID_35_)' },
  st35: { fill: 'url(#SVGID_36_)' },
  st36: { fill: 'url(#SVGID_37_)' },
  st37: { fill: 'url(#SVGID_38_)' },
  st38: { fill: 'url(#SVGID_39_)' },
  st39: { fill: 'url(#SVGID_40_)' },
  st40: { fill: 'url(#SVGID_41_)' },
  st41: { fill: 'url(#SVGID_42_)' },
  st42: { fill: 'url(#SVGID_43_)' },
  st43: { fill: 'url(#SVGID_44_)' },
  st44: { fill: 'url(#SVGID_45_)' },
  st45: { fill: 'url(#SVGID_46_)' },
  st46: { fill: 'url(#SVGID_47_)' },
  st47: { fill: 'url(#SVGID_48_)' },
  st48: { fill: 'url(#SVGID_49_)' },
  st49: { fill: 'url(#SVGID_50_)' },
  st50: { fill: 'url(#SVGID_51_)' },
  st51: { fill: 'url(#SVGID_52_)' },
  st52: { fill: 'url(#SVGID_53_)' },
  st53: { fill: 'url(#SVGID_54_)' },
  st54: { fill: 'url(#SVGID_55_)' },
  st55: { fill: 'url(#SVGID_56_)' },
  st56: { fill: 'url(#SVGID_57_)' },
  st57: { fill: 'url(#SVGID_58_)' },
  st58: { fill: 'url(#SVGID_59_)' },
  st59: { fill: 'url(#SVGID_60_)' },
  st60: { fill: 'url(#SVGID_61_)' },
  st61: { fill: 'url(#SVGID_62_)' },
  st62: { fill: 'url(#SVGID_63_)' },
  st63: { fill: 'url(#SVGID_64_)' },
  st64: { fill: 'url(#SVGID_65_)' },
  st65: { fill: 'url(#SVGID_66_)' },
}));
