import {ROLE} from "@types";

export const ROLES = {
  ALL: [ROLE.GUEST, ROLE.USER, ROLE.ADMIN, ROLE.SUPER_ADMIN],
  USERS: [ROLE.USER, ROLE.ADMIN, ROLE.SUPER_ADMIN],
  ADMINS: [ROLE.ADMIN, ROLE.SUPER_ADMIN],
  SUPER_ADMINS: [ROLE.SUPER_ADMIN],
  GUESTS: [ROLE.GUEST],
};
